### PR TITLE
Add support for show-paren-mode

### PR DESCRIPTION
**Pull request by magcius**

### CODE REVIEW

**Comment by jonathanchu** [comment]
Thanks for this @magcius! :)

I think the `atom-one-dark-bg-hl` color might be too subtle to notice the parens matching - what do you think? 

screenshot 2016-03-25 11 46 17

Also, I had to turn off `global-hl-line-mode` in my config as it would be unnoticeable for parens matching on the same line due to [this line](https://github.com/jonathanchu/atom-one-dark-theme/blob/1297cfb3d01b7ea051cf4abaa27ed4c3b4aca282/atom-one-dark-theme.el#L63) from the color theme.

Do you think it should be the `atom-one-dark-accent` color here instead?  Let me know your thoughts!

**Comment by magcius** [comment]
Ah. I use `show-paren-style expression`, which is quite visible to me:

Screenshot

**Comment by magcius** [comment]
accent is quite unreadable to me, at least in expression mode -- the subtle highlighting of paren expressions seems to match what Atom does as well.

Here's accent in my setup, which is far too busy:

screenshot from 2016-03-25 09-10-53

**Comment by jonathanchu** [comment]
@magcius Yeah, I agree, that does look bad and is distracting.  Let me give this some thought as I didn't consider the discrepancies with `show-paren-style`, whether it's an expression or the parenthesis itself.

I just looked up what the original atom-one-dark theme's method of handling this, and they actually do use the accent color to signify paren matches, too.

Any ideas you have here are more than welcomed! :)

**Comment by jonathanchu** [comment]
@magcius I'm sorry this took me so long to reply.  😱  

I'm inclined to keep the highlight color the same here as it is consistent with the actual Atom One Dark theme (which the goal of this whole thing is to try and port over the theme as close as possible).  Perhaps this can just be a custom setting in your config to override the color?  

Going to close this out now, but I'm more than happy to keep discussing if you want to re-open. :beers:

**Comment by magcius** [comment]
Yeah, I've had a fork with my changes in it for quite some time. I think the "best" case scenario would be to have paren-mode choose two different colors depending on the highlight mode. I think leaving it the way it is is fine though.

**Pull request closed without merging**
