### PR TITLE
Centaur tabs

### PR DESCRIPTION
**Pull request by ema2159**
Themed my plugin centaur-tabs, and made it's bar match the doom-modeline's bar. It looks like this:
DeepinScreenshot_select-area_20190704234510

### CODE REVIEW

**Review by jonathanchu — APPROVED** [review]
😍

**Comment by ema2159** [comment]
Daaaaaaaamn that was incredibly quick JAJA!

**Comment by jonathanchu** [comment]
Thanks so much @ema2159! Literally just installed centaur-tabs a few hours ago and loving it.  Fantastic work there and thank you so much for those contributions!

https://github.com/jonathanchu/dotemacs/commit/3341b7be172fcbc8b343487c6b89ee6f6bf3fc61

**Comment by ema2159** [comment]
My pleasure man! FYI it has just been uploaded to MELPA. Let's hope everybody enjoy my package as much as I do working on it!

**Comment by jonathanchu** [comment]
@ema2159 Oh wow, that's awesome! When I checked before it wasn't there yet, so you must have just done it! 😛 

Keep up the great work on this!  I'm looking forward to helping contribute with centaur-tabs too!  I think a big part that the Emacs community is lacking in is with aesthetic improvements like this - and I, for one, greatly welcome this!

**Comment by ema2159** [comment]
I really appreciate this kind of encouragement and your help is more than welcome! I think `centaur-tabs` can improve a lot with the help of experienced Emacs users and Elisp programmers like you. Thanks very much Jonathan!

**Pull request merged**
